### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by druhin-arrcus** [mre/kafka-influxdb#47]
I get the following error when trying to install with pip:

```Downloading/unpacking kafka_influxdb
  Downloading kafka_influxdb-0.8.0.tar.gz
  Running setup.py (path:/tmp/pip-build-9OWeIW/kafka-influxdb/setup.py) egg_info for package kafka-influxdb
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-9OWeIW/kafka-influxdb/setup.py", line 15, in <module>
        long_description = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-9OWeIW/kafka-influxdb/setup.py", line 15, in <module>

    long_description = open('README.md').read()

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-9OWeIW/kafka-influxdb
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by mre** [comment]
Whoops. Sorry. Please try again. 😀

**Comment by mre** [comment]
Should be resolved now. If not, please reopen.
