### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by mrafeeq** [mre/kafka-influxdb#64]
```
➜  kafka-influxdb git:(master) ✗ make RUNTIME=py3
python setup.py test
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'pytest'
make: *** [test] Error 1
```

Then i tried 
`pip3 install -r requirements.txt` . i got the error below 
....
.....
```
Collecting futures==3.2.0 (from -r requirements.txt (line 12))
  Could not find a version that satisfies the requirement futures==3.2.0 (from -r requirements.txt (line 12)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures==3.2.0 (from -r requirements.txt (line 12))
```

**Comment by mre** [comment]
Can you try a `git pull origin master` before the `make RUNTIME=py3`?
I removed the dependency on `futures` from the `requirements.txt` two days ago.

**Comment by mrafeeq** [comment]
Yes this solved the issue,i was able to build the image , however when i try to run the container i get the below error.  my kafka and influx containers are running separately as different containers

➜  kafka-influxdb git:(master) docker run mre0/kafka-influxdb
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/kafka_influxdb/__main__.py", line 75, in <module>
    main()
  File "/usr/src/app/kafka_influxdb/__main__.py", line 22, in main
    start_consumer(config)
  File "/usr/src/app/kafka_influxdb/__main__.py", line 54, in start_consumer
    client.consume()
  File "/usr/src/app/kafka_influxdb/worker.py", line 37, in consume
    self.init_database()
  File "/usr/src/app/kafka_influxdb/worker.py", line 75, in init_database
    self.writer.create_database(self.config.influxdb_dbname)
  File "/usr/src/app/kafka_influxdb/writer/influxdb_writer.py", line 78, in create_database
    self.client.create_database(dbname)
  File "/usr/local/lib/python3.6/site-packages/influxdb/client.py", line 559, in create_database
    self.query("CREATE DATABASE {0}".format(quote_ident(dbname)))
  File "/usr/local/lib/python3.6/site-packages/influxdb/client.py", line 394, in query
    expected_response_code=expected_response_code
  File "/usr/local/lib/python3.6/site-packages/influxdb/client.py", line 252, in request
    timeout=self._timeout
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 433, in prepare_request
    headers=merge_setting(request.headers, self.headers, dict_class=CaseInsensitiveDict),
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 69, in merge_setting
    merged_setting = dict_class(to_key_val_list(session_setting))
  File "/usr/local/lib/python3.6/site-packages/requests/structures.py", line 46, in __init__
    self.update(data, **kwargs)
  File "/usr/local/lib/python3.6/_collections_abc.py", line 847, in update
    self[key] = value
  File "/usr/local/lib/python3.6/site-packages/requests/structures.py", line 51, in __setitem__
    self._store[key.lower()] = (key, value)
KeyboardInterrupt

**Comment by mre** [comment]
Wait, there's a `KeyboardInterrupt`, which means you stopped the process, right?
It might just be working as expected?
Try with 
```docker run mre0/kafka-influxdb --verbose```

Also check that your InfluxDB is reachable.
